from collections.abc import (
    Iterator,
    Mapping,
)
from typing import Any, overload

class ErrorList:
    warnings: list[str]
    errors: list[str]

    def __init__(self) -> None: ...
    def emplace_warning(self, warning: str) -> None: ...
    def emplace_error(self, error: str) -> None: ...
    def merge(self, rhs: ErrorList) -> None: ...
    def has_errors(self) -> bool: ...

class JsonValue:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: Any) -> None: ...
    @property
    def value(self) -> Any: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    @overload
    def __getitem__(self, key: str) -> Any: ...
    @overload
    def __getitem__(self, index: int) -> Any: ...
    def keys(self) -> Any: ...
    def items(self) -> Any: ...
    def values(self) -> Any: ...
    def is_null(self) -> bool: ...
    def is_number(self) -> bool: ...
    def is_bool(self) -> bool: ...
    def is_string(self) -> bool: ...
    def is_object(self) -> bool: ...
    def is_array(self) -> bool: ...
    def is_double(self) -> bool: ...
    def is_uint64(self) -> bool: ...
    def is_int64(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

class ExtensibleObject:
    @property
    def extras(self) -> dict[str, Any]: ...
    @extras.setter
    def extras(self, value: dict[str, Any]) -> None: ...
    @property
    def unknown_properties(self) -> dict[str, Any]: ...
    @unknown_properties.setter
    def unknown_properties(self, value: dict[str, Any]) -> None: ...
    def get_generic_extension(self, name: str) -> Any | None: ...
    @property
    def extension_names(self) -> list[str]: ...
    @property
    def size_bytes(self) -> int: ...

class Uri:
    @overload
    def __init__(self, uri: str) -> None: ...
    @overload
    def __init__(
        self, base: Uri, relative: str, use_base_query: bool = False
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    @property
    def string(self) -> str: ...
    @property
    def valid(self) -> bool: ...
    @property
    def scheme(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, value: str) -> None: ...
    @property
    def file_name(self) -> str: ...
    @property
    def stem(self) -> str: ...
    @property
    def extension(self) -> str: ...
    @property
    def query(self) -> str: ...
    @query.setter
    def query(self, value: str) -> None: ...
    def ensure_trailing_slash(self) -> None: ...
    @staticmethod
    def unix_path_to_uri_path(path: str) -> str: ...
    @staticmethod
    def windows_path_to_uri_path(path: str) -> str: ...
    @staticmethod
    def native_path_to_uri_path(path: str) -> str: ...
    @staticmethod
    def uri_path_to_native_path(path: str) -> str: ...
    @staticmethod
    def resolve(
        base: str,
        relative: str,
        use_base_query: bool = False,
        assume_https_default: bool = True,
    ) -> str: ...
    @staticmethod
    def add_query(uri: str, key: str, value: str) -> str: ...
    @staticmethod
    def query_value(uri: str, key: str) -> str: ...
    @staticmethod
    def escape(uri: str) -> str: ...
    @staticmethod
    def unescape(uri: str) -> str: ...
    @staticmethod
    def substitute_template_parameters(
        template_uri: str, substitutions: Mapping[str, str]
    ) -> str: ...
    @staticmethod
    def uri_path_to_unix_path(path: str) -> str: ...
    @staticmethod
    def uri_path_to_windows_path(path: str) -> str: ...
    @staticmethod
    def path_from_uri(uri: str) -> str: ...
    @staticmethod
    def with_path(uri: str, path: str) -> str: ...

class UriQuery:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, query: str) -> None: ...
    @overload
    def __init__(self, uri: Uri) -> None: ...
    @property
    def query_string(self) -> str: ...
    def get(self, key: str, default: str | None = None) -> str | None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...

class Color:
    r: int
    g: int
    b: int
    a: int

    def __init__(self, r: int, g: int, b: int, a: int = 0xFF) -> None: ...
    def to_rgba32(self) -> int: ...

class CreditFilteringMode:
    NONE: int
    UNIQUE_HTML_AND_SHOW_ON_SCREEN: int
    UNIQUE_HTML: int

class Credit:
    def __eq__(self, other: object) -> bool: ...

class CreditsSnapshot:
    @property
    def current_credits(self) -> list: ...
    @property
    def removed_credits(self) -> list: ...

class CreditSystem:
    def __init__(self) -> None: ...
    def should_be_shown_on_screen(self, credit: Credit) -> bool: ...
    def set_show_on_screen(self, credit: Credit, show_on_screen: bool) -> None: ...
    def html(self, credit: Credit) -> str: ...
    def create_credit(
        self, source: CreditSource, html: str, show_on_screen: bool = False
    ) -> Credit: ...
    def get_credit_source(self, credit: Credit) -> CreditSource | None: ...
    def add_credit_reference(self, credit: Credit) -> None: ...
    def remove_credit_reference(self, credit: Credit) -> None: ...
    def get_snapshot(
        self, filtering_mode: CreditFilteringMode = ...
    ) -> CreditsSnapshot: ...

class CreditSource:
    def __init__(self, credit_system: CreditSystem) -> None: ...
    @property
    def credit_system(self) -> CreditSystem | None: ...

class CreditReferencer:
    def __init__(self, credit_system: CreditSystem | None = None) -> None: ...
    @property
    def credit_system(self) -> CreditSystem | None: ...
    def set_credit_system(self, credit_system: CreditSystem) -> None: ...
    def add_credit_reference(self, credit: Credit) -> None: ...
    def release_all_references(self) -> None: ...
    def is_credit_referenced(self, credit: Credit) -> bool: ...

class Math:
    EPSILON1: float
    EPSILON2: float
    EPSILON3: float
    EPSILON4: float
    EPSILON5: float
    EPSILON6: float
    EPSILON7: float
    EPSILON8: float
    EPSILON9: float
    EPSILON10: float
    EPSILON11: float
    EPSILON12: float
    EPSILON13: float
    EPSILON14: float
    EPSILON15: float
    EPSILON16: float
    EPSILON17: float
    EPSILON18: float
    EPSILON19: float
    EPSILON20: float
    EPSILON21: float
    ONE_PI: float
    TWO_PI: float
    PI_OVER_TWO: float
    PI_OVER_FOUR: float
    GOLDEN_RATIO: float
    @staticmethod
    def equals_epsilon(
        left: float,
        right: float,
        relative_epsilon: float,
        absolute_epsilon: float,
    ) -> bool: ...
    @staticmethod
    def sign(value: float) -> float: ...
    @staticmethod
    def sign_not_zero(value: float) -> float: ...
    @staticmethod
    def negative_pi_to_pi(angle: float) -> float: ...
    @staticmethod
    def zero_to_two_pi(angle: float) -> float: ...
    @staticmethod
    def mod(m: float, n: float) -> float: ...
    @staticmethod
    def degrees_to_radians(angle_degrees: float) -> float: ...
    @staticmethod
    def radians_to_degrees(angle_radians: float) -> float: ...
    @staticmethod
    def lerp(p: float, q: float, time: float) -> float: ...
    @staticmethod
    def clamp(value: float, min: float, max: float) -> float: ...
    @staticmethod
    def to_snorm(value: float, range_maximum: float = 255.0) -> float: ...
    @staticmethod
    def from_snorm(value: float, range_maximum: float = 255.0) -> float: ...
    @staticmethod
    def convert_longitude_range(angle: float) -> float: ...
    @staticmethod
    def round_up(value: float, tolerance: float) -> float: ...
    @staticmethod
    def round_down(value: float, tolerance: float) -> float: ...

def is_gzip(data: bytes) -> bool: ...
def gzip(data: bytes) -> bytes: ...
def gunzip(data: bytes) -> bytes: ...

class AttributeCompression:
    @staticmethod
    def oct_decode(x: int, y: int) -> tuple[float, float, float]: ...
    @staticmethod
    def decode_rgb565(value: int) -> tuple[float, float, float]: ...
