from __future__ import annotations

from enum import IntEnum
from typing import Any

class ExtensionState(IntEnum):
    Enabled = ...
    JsonOnly = ...
    Disabled = ...

class JsonReaderOptions:
    capture_unknown_properties: bool
    def extension_state(self, extension_name: str) -> ExtensionState: ...
    def set_extension_state(
        self, extension_name: str, new_state: ExtensionState
    ) -> None: ...

def read_json_value(data: bytes) -> dict[str, Any]: ...
