from __future__ import annotations

from typing import Any

from .reader import ExtensionState

class ExtensionWriterContext:
    def __init__(self) -> None: ...
    def extension_state(self, extension_name: str) -> ExtensionState: ...
    def set_extension_state(
        self, extension_name: str, new_state: ExtensionState
    ) -> None: ...

class JsonWriter:
    def __init__(self) -> None: ...
    def null(self) -> None: ...
    def bool(self, value: bool) -> None: ...
    def int(self, value: int) -> None: ...
    def uint(self, value: int) -> None: ...
    def int64(self, value: int) -> None: ...
    def uint64(self, value: int) -> None: ...
    def double(self, value: float) -> None: ...
    def key(self, key: str) -> None: ...
    def string(self, value: str) -> None: ...
    def start_object(self) -> None: ...
    def end_object(self) -> None: ...
    def start_array(self) -> None: ...
    def end_array(self) -> None: ...
    def to_string(self) -> str: ...
    def to_bytes(self) -> bytes: ...
    def errors(self) -> list[str]: ...
    def warnings(self) -> list[str]: ...

class PrettyJsonWriter(JsonWriter):
    def __init__(self) -> None: ...

def write_json_value(value: Any, writer: JsonWriter) -> None: ...
def dumps_pretty(value: Any) -> str: ...
