from __future__ import annotations

from collections.abc import Callable, Iterator, Mapping, Sequence
from enum import IntEnum
from typing import Any, Optional, Union, overload

import numpy as np
import numpy.typing as npt

from ..utility import ExtensibleObject

class VertexAttributeSemantics:
    POSITION: str
    NORMAL: str
    TANGENT: str
    @staticmethod
    def TEXCOORD(index: int = 0) -> str: ...
    @staticmethod
    def COLOR(index: int = 0) -> str: ...
    @staticmethod
    def JOINTS(index: int = 0) -> str: ...
    @staticmethod
    def WEIGHTS(index: int = 0) -> str: ...
    @staticmethod
    def FEATURE_ID(index: int = 0) -> str: ...

class Asset:
    copyright: Optional[str]
    generator: Optional[str]
    version: str
    min_version: Optional[str]
    def __repr__(self) -> str: ...

class BufferCesium:
    @property
    def data(self) -> npt.NDArray[np.uint8]: ...
    @data.setter
    def data(self, value: npt.NDArray[np.uint8]) -> None: ...

class Buffer:
    name: str
    uri: Optional[str]
    byte_length: int
    cesium: BufferCesium
    @property
    def size_bytes(self) -> int: ...
    def __repr__(self) -> str: ...

class BufferView:
    class Target:
        ARRAY_BUFFER: int
        ELEMENT_ARRAY_BUFFER: int

    name: str
    buffer: int
    byte_offset: int
    byte_length: int
    byte_stride: Optional[int]
    target: Optional[int]
    def __repr__(self) -> str: ...

class AccessorSparseValues:
    buffer_view: int
    byte_offset: int

class AccessorSparseIndices:
    class ComponentType:
        UNSIGNED_BYTE: int
        UNSIGNED_SHORT: int
        UNSIGNED_INT: int

    buffer_view: int
    byte_offset: int
    component_type: int

class AccessorSparse:
    count: int
    indices: AccessorSparseIndices
    values: AccessorSparseValues

class Accessor:
    class ComponentType:
        BYTE: int
        UNSIGNED_BYTE: int
        SHORT: int
        UNSIGNED_SHORT: int
        UNSIGNED_INT: int
        FLOAT: int
        INT: int
        INT64: int
        UNSIGNED_INT64: int
        DOUBLE: int

    class Type:
        SCALAR: str
        VEC2: str
        VEC3: str
        VEC4: str
        MAT2: str
        MAT3: str
        MAT4: str

    name: str
    buffer_view: int
    byte_offset: int
    component_type: int
    normalized: bool
    count: int
    type: str
    max: list[float]
    min: list[float]
    sparse: Optional[AccessorSparse]

    def compute_number_of_components(self) -> int: ...
    def compute_byte_size_of_component(self) -> int: ...
    def compute_bytes_per_vertex(self) -> int: ...
    def compute_byte_stride(self, model: Model) -> int: ...
    def __repr__(self) -> str: ...

class TextureInfo:
    index: int
    tex_coord: int

class MaterialNormalTextureInfo:
    index: int
    tex_coord: int
    scale: float

class MaterialOcclusionTextureInfo:
    index: int
    tex_coord: int
    strength: float

class MaterialPBRMetallicRoughness:
    base_color_factor: list[float]
    base_color_texture: Optional[TextureInfo]
    metallic_factor: float
    roughness_factor: float
    metallic_roughness_texture: Optional[TextureInfo]

class Material:
    class AlphaMode:
        OPAQUE: str
        MASK: str
        BLEND: str

    name: str
    pbr_metallic_roughness: Optional[MaterialPBRMetallicRoughness]
    normal_texture: Optional[MaterialNormalTextureInfo]
    occlusion_texture: Optional[MaterialOcclusionTextureInfo]
    emissive_texture: Optional[TextureInfo]
    emissive_factor: list[float]
    alpha_mode: str
    alpha_cutoff: float
    double_sided: bool
    @property
    def ext_materials_unlit(self) -> Optional[ExtKhrMaterialsUnlit]: ...
    def __repr__(self) -> str: ...

class MeshPrimitive:
    class Mode:
        POINTS: int
        LINES: int
        LINE_LOOP: int
        LINE_STRIP: int
        TRIANGLES: int
        TRIANGLE_STRIP: int
        TRIANGLE_FAN: int

    attributes: dict[str, int]
    indices: int
    material: int
    mode: int
    targets: list[dict[str, int]]
    @property
    def ext_mesh_features(self) -> Optional[ExtMeshFeatures]: ...
    @property
    def ext_structural_metadata(
        self,
    ) -> Optional[MeshPrimitiveExtStructuralMetadata]: ...
    @property
    def ext_khr_gaussian_splatting(
        self,
    ) -> Optional[ExtKhrGaussianSplatting]: ...
    def __repr__(self) -> str: ...

class Mesh:
    name: str
    primitives: list[MeshPrimitive]
    weights: list[float]
    def __repr__(self) -> str: ...

class Texture:
    name: str
    sampler: int
    source: int
    def __repr__(self) -> str: ...

class ImageAsset:
    width: int
    height: int
    channels: int
    bytes_per_channel: int
    compressed_pixel_format: GpuCompressedPixelFormat
    mip_positions: list[ImageAssetMipPosition]
    @property
    def pixel_data(self) -> npt.NDArray[np.uint8]: ...
    @pixel_data.setter
    def pixel_data(self, value: npt.NDArray[np.uint8]) -> None: ...
    size_bytes: int
    @property
    def computed_size_bytes(self) -> int: ...
    def change_number_of_channels(
        self, new_channels: int, default_value: int = 0
    ) -> None: ...
    def __repr__(self) -> str: ...

class Image:
    name: str
    uri: Optional[str]
    mime_type: Optional[str]
    buffer_view: int
    @property
    def asset(self) -> ImageAsset | None: ...

class Sampler:
    class MagFilter:
        NEAREST: int
        LINEAR: int

    class MinFilter:
        NEAREST: int
        LINEAR: int
        NEAREST_MIPMAP_NEAREST: int
        LINEAR_MIPMAP_NEAREST: int
        NEAREST_MIPMAP_LINEAR: int
        LINEAR_MIPMAP_LINEAR: int

    class WrapS:
        CLAMP_TO_EDGE: int
        MIRRORED_REPEAT: int
        REPEAT: int

    class WrapT:
        CLAMP_TO_EDGE: int
        MIRRORED_REPEAT: int
        REPEAT: int

    name: str
    mag_filter: Optional[int]
    min_filter: Optional[int]
    wrap_s: int
    wrap_t: int
    def __repr__(self) -> str: ...

class Node:
    name: str
    camera: int
    children: list[int]
    skin: int
    matrix: list[float]
    mesh: int
    rotation: list[float]
    scale: list[float]
    translation: list[float]
    weights: list[float]
    @property
    def ext_mesh_gpu_instancing(self) -> Optional[ExtMeshGpuInstancing]: ...
    def __repr__(self) -> str: ...

class Scene:
    name: str
    nodes: list[int]
    def __repr__(self) -> str: ...

class Skin:
    name: str
    inverse_bind_matrices: int
    skeleton: int
    joints: list[int]
    def __repr__(self) -> str: ...

class CameraOrthographic:
    xmag: float
    ymag: float
    zfar: float
    znear: float

class CameraPerspective:
    aspect_ratio: Optional[float]
    yfov: float
    zfar: Optional[float]
    znear: float

class GltfCamera:
    class Type:
        perspective: str
        orthographic: str

    name: str
    orthographic: Optional[CameraOrthographic]
    perspective: Optional[CameraPerspective]
    type: str
    def __repr__(self) -> str: ...

class AnimationChannelTarget:
    class Path:
        translation: str
        rotation: str
        scale: str
        weights: str

    node: int
    path: str

class AnimationChannel:
    sampler: int
    target: AnimationChannelTarget
    def __repr__(self) -> str: ...

class AnimationSampler:
    class Interpolation:
        LINEAR: str
        STEP: str
        CUBICSPLINE: str

    input: int
    interpolation: str
    output: int
    def __repr__(self) -> str: ...

class Animation:
    name: str
    channels: list[AnimationChannel]
    samplers: list[AnimationSampler]
    def __repr__(self) -> str: ...

class Model(ExtensibleObject):
    accessors: list[Accessor]
    animations: list[Animation]
    asset: Asset
    buffers: list[Buffer]
    buffer_views: list[BufferView]
    cameras: list[GltfCamera]
    images: list[Image]
    materials: list[Material]
    meshes: list[Mesh]
    nodes: list[Node]
    samplers: list[Sampler]
    scene: int
    scenes: list[Scene]
    skins: list[Skin]
    textures: list[Texture]
    extensions_used: list[str]
    extensions_required: list[str]
    @property
    def size_bytes(self) -> int: ...
    def add_extension_used(self, extension: str) -> None: ...
    def add_extension_required(self, extension: str) -> None: ...
    def remove_extension_used(self, extension: str) -> None: ...
    def remove_extension_required(self, extension: str) -> None: ...
    def is_extension_used(self, extension: str) -> bool: ...
    def is_extension_required(self, extension: str) -> bool: ...
    def generate_missing_normals_smooth(self) -> None: ...
    def merge(self, other: Model) -> ...: ...
    def for_each_root_node_in_scene(
        self,
        scene_id: int,
        callback: Callable[[Model, Node], None],
    ) -> None: ...
    def for_each_node_in_scene(
        self,
        scene_id: int,
        callback: Callable[[Model, Node, npt.NDArray[np.float64]], None],
    ) -> None: ...
    def for_each_primitive_in_scene(
        self,
        scene_id: int,
        callback: Callable[
            [Model, Node, Mesh, MeshPrimitive, npt.NDArray[np.float64]], None
        ],
    ) -> None: ...
    @property
    def ext_structural_metadata(
        self,
    ) -> Optional[ModelExtStructuralMetadata]: ...
    def get_or_create_ext_structural_metadata(
        self,
    ) -> ModelExtStructuralMetadata: ...
    @property
    def ext_cesium_rtc(self) -> Optional[ExtCesiumRTC]: ...
    def __repr__(self) -> str: ...

class GpuCompressedPixelFormat(IntEnum):
    NONE = ...
    ETC1_RGB = ...
    ETC2_RGBA = ...
    BC1_RGB = ...
    BC3_RGBA = ...
    BC4_R = ...
    BC5_RG = ...
    BC7_RGBA = ...
    PVRTC1_4_RGB = ...
    PVRTC1_4_RGBA = ...
    ASTC_4x4_RGBA = ...
    PVRTC2_4_RGB = ...
    PVRTC2_4_RGBA = ...
    ETC2_EAC_R11 = ...
    ETC2_EAC_RG11 = ...

class SupportedGpuCompressedPixelFormats:
    ETC1_RGB: bool
    ETC2_RGBA: bool
    BC1_RGB: bool
    BC3_RGBA: bool
    BC4_R: bool
    BC5_RG: bool
    BC7_RGBA: bool
    PVRTC1_4_RGB: bool
    PVRTC1_4_RGBA: bool
    ASTC_4x4_RGBA: bool
    PVRTC2_4_RGB: bool
    PVRTC2_4_RGBA: bool
    ETC2_EAC_R11: bool
    ETC2_EAC_RG11: bool
    def __init__(self) -> None: ...

class Ktx2TranscodeTargets:
    ETC1S_R: GpuCompressedPixelFormat
    ETC1S_RG: GpuCompressedPixelFormat
    ETC1S_RGB: GpuCompressedPixelFormat
    ETC1S_RGBA: GpuCompressedPixelFormat
    UASTC_R: GpuCompressedPixelFormat
    UASTC_RG: GpuCompressedPixelFormat
    UASTC_RGB: GpuCompressedPixelFormat
    UASTC_RGBA: GpuCompressedPixelFormat
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        supported_formats: SupportedGpuCompressedPixelFormats,
        preserve_high_quality: bool,
    ) -> None: ...

class PropertyType(IntEnum):
    Invalid = ...
    Scalar = ...
    Vec2 = ...
    Vec3 = ...
    Vec4 = ...
    Mat2 = ...
    Mat3 = ...
    Mat4 = ...
    String = ...
    Boolean = ...
    Enum = ...

class PropertyComponentType(IntEnum):
    NONE = ...
    Int8 = ...
    Uint8 = ...
    Int16 = ...
    Uint16 = ...
    Int32 = ...
    Uint32 = ...
    Int64 = ...
    Uint64 = ...
    Float32 = ...
    Float64 = ...

class PropertyTableViewStatus(IntEnum):
    Valid = ...
    ErrorMissingMetadataExtension = ...
    ErrorMissingSchema = ...
    ErrorClassNotFound = ...

class PropertyColumnAccessor(Sequence[Any]):
    @property
    def status(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __array__(self, dtype: Any = None) -> Union[npt.NDArray, list]: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> Any: ...
    @overload
    def __getitem__(self, index: slice) -> Sequence[Any]: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class PropertyTableView(Mapping[str, PropertyColumnAccessor]):
    def __init__(self, model: Model, property_table: Any) -> None: ...
    @property
    def status(self) -> PropertyTableViewStatus: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def size(self) -> int: ...
    def get_class_property(self, property_id: str) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, property_id: str) -> PropertyColumnAccessor: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class PropertyTextureViewStatus(IntEnum):
    Valid = ...
    ErrorMissingMetadataExtension = ...
    ErrorMissingSchema = ...
    ErrorClassNotFound = ...

class TexturePropertyAccessor:
    @property
    def status(self) -> int: ...
    def get(self, u: float, v: float) -> Any: ...
    def get_raw(self, u: float, v: float) -> Any: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class PropertyTextureView:
    def __init__(self, model: Model, property_texture: Any) -> None: ...
    @property
    def status(self) -> PropertyTextureViewStatus: ...
    @property
    def name(self) -> Optional[str]: ...
    def get_class_property(self, property_id: str) -> Any: ...
    def get_property_view(self, property_id: str) -> TexturePropertyAccessor: ...
    def __contains__(self, property_id: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class PropertyAttributeViewStatus(IntEnum):
    Valid = ...
    ErrorMissingMetadataExtension = ...
    ErrorMissingSchema = ...
    ErrorClassNotFound = ...

class AttributePropertyAccessor:
    @property
    def status(self) -> int: ...
    @property
    def size(self) -> int: ...
    def get(self, index: int) -> Any: ...
    def get_raw(self, index: int) -> Any: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class PropertyAttributeView:
    def __init__(self, model: Model, property_attribute: Any) -> None: ...
    @property
    def status(self) -> PropertyAttributeViewStatus: ...
    @property
    def name(self) -> Optional[str]: ...
    def get_class_property(self, property_id: str) -> Any: ...
    def get_property_view(
        self, primitive: MeshPrimitive, property_id: str
    ) -> AttributePropertyAccessor: ...
    def __contains__(self, property_id: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class FeatureIdTextureViewStatus(IntEnum):
    Valid = ...
    ErrorUninitialized = ...
    ErrorInvalidTexture = ...
    ErrorInvalidImage = ...
    ErrorInvalidSampler = ...
    ErrorEmptyImage = ...
    ErrorInvalidImageBytesPerChannel = ...
    ErrorInvalidChannels = ...

class FeatureIdTextureView:
    def __init__(self, model: Model, feature_id_texture: Any) -> None: ...
    @property
    def status(self) -> FeatureIdTextureViewStatus: ...
    @property
    def channels(self) -> list[int]: ...
    def __call__(self, u: float, v: float) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class InstanceAttributeSemantics:
    TRANSLATION: str
    ROTATION: str
    SCALE: str
    FEATURE_ID_n: list[str]

class KhrTextureTransformStatus(IntEnum):
    VALID = ...
    ERROR_INVALID_OFFSET = ...
    ERROR_INVALID_SCALE = ...

class KhrTextureTransform:
    def __init__(self) -> None: ...
    @property
    def status(self) -> KhrTextureTransformStatus: ...
    @property
    def offset(self) -> tuple[float, float]: ...
    @property
    def rotation(self) -> float: ...
    @property
    def rotation_sine_cosine(self) -> tuple[float, float]: ...
    @property
    def scale(self) -> tuple[float, float]: ...
    def apply_transform(self, u: float, v: float) -> tuple[float, float]: ...
    @property
    def tex_coord_set_index(self) -> int | None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class TextureViewStatus(IntEnum):
    VALID = ...
    ERROR_UNINITIALIZED = ...
    ERROR_INVALID_TEXTURE = ...
    ERROR_INVALID_SAMPLER = ...
    ERROR_INVALID_IMAGE = ...
    ERROR_EMPTY_IMAGE = ...
    ERROR_INVALID_BYTES_PER_CHANNEL = ...

class TextureViewOptions:
    apply_khr_texture_transform_extension: bool
    make_image_copy: bool
    def __init__(self) -> None: ...

class TextureView:
    def __init__(
        self,
        model: Model,
        texture_info: TextureInfo,
        options: TextureViewOptions = ...,
    ) -> None: ...
    @property
    def status(self) -> TextureViewStatus: ...
    @property
    def tex_coord_set_index(self) -> int: ...
    @property
    def image(self) -> ImageAsset | None: ...
    @property
    def texture_transform(self) -> KhrTextureTransform | None: ...
    def sample_nearest_pixel(
        self, u: float, v: float, channels: list[int]
    ) -> list[int]: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewStatus(IntEnum):
    VALID = ...
    INVALID_ACCESSOR_INDEX = ...
    INVALID_BUFFER_VIEW_INDEX = ...
    INVALID_BUFFER_INDEX = ...
    BUFFER_VIEW_TOO_SMALL = ...
    BUFFER_TOO_SMALL = ...
    WRONG_SIZE_T = ...
    INVALID_TYPE = ...
    INVALID_COMPONENT_TYPE = ...
    INVALID_BYTE_STRIDE = ...

class AccessorViewFloat:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewDouble:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewInt8:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewUInt8:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewInt16:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewUInt16:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewInt32:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewUInt32:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewVec2:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewVec3:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewVec4:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewDVec2:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewDVec3:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewDVec4:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorViewMat4:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    @property
    def stride(self) -> int: ...
    @property
    def offset(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __array__(self, dtype: Any = None) -> npt.NDArray: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

_AnyAccessorView = (
    AccessorViewFloat
    | AccessorViewDouble
    | AccessorViewInt8
    | AccessorViewUInt8
    | AccessorViewInt16
    | AccessorViewUInt16
    | AccessorViewInt32
    | AccessorViewUInt32
    | AccessorViewVec2
    | AccessorViewVec3
    | AccessorViewVec4
    | AccessorViewDVec2
    | AccessorViewDVec3
    | AccessorViewDVec4
    | AccessorViewMat4
)

def AccessorView(model: Model, accessor_index: int) -> _AnyAccessorView:
    """Create a typed AccessorView, auto-detecting type from the accessor.

    Use ``np.array(view)`` for a zero-copy numpy array into the glTF buffer.

    Raises:
        ValueError: If the accessor index is out of range or the underlying
            buffer data is invalid (e.g. buffer too small, bad byte stride).
        TypeError: If the accessor's type/componentType combination is not
            supported.
    """
    ...

class AccessorWriterFloat:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterDouble:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterInt8:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterUInt8:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterInt16:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterUInt16:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterInt32:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

def get_position_accessor_view(
    model: Model, primitive: MeshPrimitive
) -> npt.NDArray[np.float32] | None:
    """Get the position accessor as an (N,3) float32 numpy array, or None if invalid."""
    ...

def get_normal_accessor_view(
    model: Model, primitive: MeshPrimitive
) -> npt.NDArray[np.float32] | None:
    """Get the normal accessor as an (N,3) float32 numpy array, or None if invalid."""
    ...

def get_index_accessor_view(model: Model, primitive: MeshPrimitive) -> object | None:
    """Get the index accessor view, or None if the primitive has no indices."""
    ...

def get_feature_id_accessor_view(
    model: Model, primitive: MeshPrimitive, feature_id_attribute_index: int
) -> object:
    """Get a feature ID accessor view for the given attribute index."""
    ...

def get_tex_coord_accessor_view(
    model: Model, primitive: MeshPrimitive, texture_coordinate_set_index: int
) -> npt.NDArray[np.float32] | None:
    """Get texture coordinates as an (N,2) numpy array."""
    ...

def get_quaternion_accessor_view(
    model: Model, accessor_index: int
) -> npt.NDArray[np.float32] | None:
    """Get quaternion accessor as an (N,4) numpy array."""
    ...

def apply_sampler_wrap_s(u: float, wrap_s: int) -> float:
    """Apply a sampler WrapS mode to a U texture coordinate."""
    ...

def apply_sampler_wrap_t(v: float, wrap_t: int) -> float:
    """Apply a sampler WrapT mode to a V texture coordinate."""
    ...

class AccessorWriterUInt32:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterVec2:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterVec3:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterVec4:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterDVec2:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterDVec3:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterDVec4:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class AccessorWriterMat4:
    def __init__(self, model: Model, accessor_index: int) -> None: ...
    @property
    def status(self) -> AccessorViewStatus: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def set_from_array(self, array: npt.NDArray) -> None: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...

class ImageAssetMipPosition:
    def __init__(self) -> None: ...
    byte_offset: int
    byte_size: int

class EnumValue(ExtensibleObject):
    def __init__(self) -> None: ...
    name: str
    description: Optional[str]
    value: int
    def __repr__(self) -> str: ...

class Enum(ExtensibleObject):
    def __init__(self) -> None: ...
    name: Optional[str]
    description: Optional[str]
    value_type: str
    values: list[EnumValue]
    def get_name(self, enum_value: int) -> Optional[str]: ...
    def __repr__(self) -> str: ...

class ClassProperty(ExtensibleObject):
    class Type:
        SCALAR: str
        VEC2: str
        VEC3: str
        VEC4: str
        MAT2: str
        MAT3: str
        MAT4: str
        STRING: str
        BOOLEAN: str
        ENUM: str

    class ComponentType:
        INT8: str
        UINT8: str
        INT16: str
        UINT16: str
        INT32: str
        UINT32: str
        INT64: str
        UINT64: str
        FLOAT32: str
        FLOAT64: str

    def __init__(self) -> None: ...
    name: Optional[str]
    description: Optional[str]
    type: str
    component_type: Optional[str]
    enum_type: Optional[str]
    array: bool
    count: Optional[int]
    normalized: bool
    required: bool
    semantic: Optional[str]
    offset: Any
    scale: Any
    max: Any
    min: Any
    no_data: Any
    default_property: Any
    def __repr__(self) -> str: ...

class MetadataClass(ExtensibleObject):
    def __init__(self) -> None: ...
    name: Optional[str]
    description: Optional[str]
    properties: dict[str, ClassProperty]
    parent: Optional[str]
    def __repr__(self) -> str: ...

class Schema:
    def __init__(self) -> None: ...
    id: str
    name: Optional[str]
    description: Optional[str]
    version: Optional[str]
    classes: dict[str, MetadataClass]
    enums: dict[str, Enum]
    @property
    def size_bytes(self) -> int: ...

class PropertyTableProperty(ExtensibleObject):
    class ArrayOffsetType:
        UINT8: str
        UINT16: str
        UINT32: str
        UINT64: str

    class StringOffsetType:
        UINT8: str
        UINT16: str
        UINT32: str
        UINT64: str

    def __init__(self) -> None: ...
    values: int
    array_offsets: int
    string_offsets: int
    array_offset_type: str
    string_offset_type: str
    offset: Any
    scale: Any
    max: Any
    min: Any

class PropertyTableSpec(ExtensibleObject):
    def __init__(self) -> None: ...
    name: Optional[str]
    class_property: str
    count: int
    properties: dict[str, PropertyTableProperty]

class PropertyTextureProperty(TextureInfo):
    def __init__(self) -> None: ...
    channels: list[int]
    offset: Any
    scale: Any
    max: Any
    min: Any

class PropertyTextureSpec(ExtensibleObject):
    def __init__(self) -> None: ...
    name: Optional[str]
    class_property: str
    properties: dict[str, PropertyTextureProperty]

class PropertyAttributeProperty(ExtensibleObject):
    def __init__(self) -> None: ...
    attribute: str
    offset: Any
    scale: Any
    max: Any
    min: Any

class PropertyAttributeSpec(ExtensibleObject):
    def __init__(self) -> None: ...
    name: Optional[str]
    class_property: str
    properties: dict[str, PropertyAttributeProperty]

class FeatureIdTexture(TextureInfo):
    def __init__(self) -> None: ...
    channels: list[int]

class FeatureId(ExtensibleObject):
    def __init__(self) -> None: ...
    feature_count: int
    null_feature_id: Optional[int]
    label: Optional[str]
    attribute: Optional[int]
    texture: Optional[FeatureIdTexture]
    property_table: int

class ExtMeshFeatures(ExtensibleObject):
    def __init__(self) -> None: ...
    feature_ids: list[FeatureId]

class MeshPrimitiveExtStructuralMetadata(ExtensibleObject):
    def __init__(self) -> None: ...
    property_textures: list[int]
    property_attributes: list[int]

class ModelExtStructuralMetadata(ExtensibleObject):
    def __init__(self) -> None: ...
    schema: Optional[Schema]
    schema_uri: Optional[str]
    property_tables: list[PropertyTableSpec]
    property_textures: list[PropertyTextureSpec]
    property_attributes: list[PropertyAttributeSpec]

class ExtMeshGpuInstancing(ExtensibleObject):
    def __init__(self) -> None: ...
    attributes: dict[str, int]

class ExtInstanceFeaturesFeatureId(ExtensibleObject):
    def __init__(self) -> None: ...
    feature_count: int
    null_feature_id: Optional[int]
    label: Optional[str]
    attribute: Optional[int]
    property_table: Optional[int]

class ExtInstanceFeatures(ExtensibleObject):
    def __init__(self) -> None: ...
    feature_ids: list[ExtInstanceFeaturesFeatureId]

class ExtKhrMaterialsUnlit(ExtensibleObject):
    """Marker extension (no fields) — KHR_materials_unlit."""
    def __init__(self) -> None: ...
    EXTENSION_NAME: str

class ExtKhrGaussianSplatting(ExtensibleObject):
    """KHR_gaussian_splatting extension on MeshPrimitive."""

    class Kernel:
        ellipse: str

    class ColorSpace:
        srgb_rec709_display: str
        lin_rec709_display: str

    class Projection:
        perspective: str

    class SortingMethod:
        cameraDistance: str

    def __init__(self) -> None: ...
    EXTENSION_NAME: str
    kernel: str
    color_space: str
    projection: str
    sorting_method: str

class ExtKhrGaussianSplattingHintsValue(ExtensibleObject):
    def __init__(self) -> None: ...
    projection: str
    sorting_method: str

class ExtKhrGaussianSplattingCompressionSpz2(ExtensibleObject):
    def __init__(self) -> None: ...
    EXTENSION_NAME: str
    buffer_view: int

class ExtCesiumRTC(ExtensibleObject):
    """CESIUM_RTC extension on Model."""
    def __init__(self) -> None: ...
    EXTENSION_NAME: str
    center: list[float]
